### ISSUE TITLE
Missing json

### ISSUE THREAD

**Issue by Eon4442** [Kqzz/MCsniperPY#3]
Missing json file

**Comment by Kqzz** [comment]
not sure what you mean. You need to create a JSON file.

**Comment by Eon4442** [comment]
what do i need to put in the json file?

**Comment by Kqzz** [comment]
its in the discord in #usage.

**Comment by Eon4442** [comment]
omfg om stupep thanks man

**Comment by Pemigrade** [comment]
Can possibly be closed?
